### ISSUE TITLE
Found a possible fix for the font install issue

### ISSUE THREAD

**Issue by unquietwiki** [ralish/PSWinGlue#1]
https://stackoverflow.com/questions/12165856/how-do-i-pass-option-flags-to-folder-copyhere-in-powershell?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Lookup the "ivision.com" suggestion on that post.

**Comment by ralish** [comment]
I don't feel this is a great solution, primarily because the font matching logic is very basic. But the author is entirely correct that the Explorer shell *Fonts* namespace appears to completely ignore any additional flags which are passed in.

I've implemented an alternate approach which completely sidesteps the Explorer shell altogether. The script now has two modes of operation, controlled by the `-Method` parameter: *Shell* and *Manual*.

The *Shell* mode is the conventional approach which delegates font installation to the Explorer shell. It makes no guarantee that it will run non-interactively due to limitations in the shell API.

The *Manual* mode performs font installation entirely through copying fonts to the correct locations and updating appropriate Registry keys. It tries to be reasonably intelligent about it and emulates the naming conventions used by the Explorer shell. It is guaranteed to run entirely non-interactively. Among other things, it will:

- Handle per-user versus per-system font installation (provided underlying OS has support)
- Parse metadata for each font to construct the appropriate file name matching Explorer's scheme
- Ensure the appropriate Registry values are added also consistent with Explorer's scheme
- Detect if a matching font is already present and skip processing it (reports an error)

I've also added two additional scripts:

- `Get-Fonts.ps1`: Enumerates fonts, returning the file and registry data for each
- `Uninstall-Font.ps1`: Handles removing fonts, including the case where they're in-use

Rant: It's ridiculous this is so damn hard and there aren't simple APIs to handle all of this.
